version:  '3.8'

services:
  mongo:
    image: mongo  
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
     image: redis:latest
     restart: always
     ports:
      - "6379:6379"
     volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
 